[package]
name = "toydb"
description = "A distributed SQL database"
version = "0.1.0"
authors = ["Erik Grinaker <erik@grinaker.org>"]
edition = "2021"
default-run = "toydb"

[lib]
doctest = false

[dependencies]
async-channel = "~2.2.0"
bincode = "~1.3.3"
clap = { version = "~4.5.4", features = ["cargo", "derive"] }
config = "~0.14.0"
derivative = "~2.2.0"
fs4 = "~0.8.1"
futures = "~0.3.15"
futures-util = "~0.3.15"
hdrhistogram = "~7.5.4"
hex = "~0.4.3"
itertools = "0.12.1"
lazy_static = "~1.4.0"
log = "~0.4.14"
petname = "1.1.3"
rand = "~0.8.3"
regex = "1.5.4"
rustyline = "~14.0.0"
rustyline-derive = "~0.10.0"
serde = "~1.0.126"
serde_bytes = "~0.11.12"
serde_derive = "~1.0.126"
simplelog = "~0.12.1"
tokio = { version = "~1.37.0", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "io-util",
    "time",
    "sync",
] }
tokio-serde = { version = "~0.9.0", features = ["bincode"] }
tokio-stream = { version = "~0.1.6", features = ["net"] }
tokio-util = { version = "~0.7.8", features = ["codec"] }
uuid = { version = "~1.8.0", features = ["v4"] }

[dev-dependencies]
escargot = "0.5.10"
goldenfile = "~1.6.0"
paste = "~1.0.14"
pretty_assertions = "~1.4.0"
serial_test = "~3.0.0"
tempdir = "~0.3.7"
tempfile = "~3.10.1"
