version: "3.7"

networks:
  toydb:
    name: toydb
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

services:
  toydb1: &toydb
    build: ..
    environment:
      - TOYDB_LOG_LEVEL
    volumes:
      - ./toydb1/toydb.yaml:/etc/toydb.yaml
      - ./toydb1/data:/var/lib/toydb
    networks:
      toydb:
        ipv4_address: 172.20.0.101
    ports:
      - 9601:9605

  toydb2:
    <<: *toydb
    volumes:
      - ./toydb2/toydb.yaml:/etc/toydb.yaml
      - ./toydb2/data:/var/lib/toydb
    networks:
      toydb:
        ipv4_address: 172.20.0.102
    ports:
      - 9602:9605

  toydb3:
    <<: *toydb
    volumes:
      - ./toydb3/toydb.yaml:/etc/toydb.yaml
      - ./toydb3/data:/var/lib/toydb
    networks:
      toydb:
        ipv4_address: 172.20.0.103
    ports:
      - 9603:9605

  toydb4:
    <<: *toydb
    volumes:
      - ./toydb4/toydb.yaml:/etc/toydb.yaml
      - ./toydb4/data:/var/lib/toydb
    networks:
      toydb:
        ipv4_address: 172.20.0.104
    ports:
      - 9604:9605

  toydb5:
    <<: *toydb
    volumes:
      - ./toydb5/toydb.yaml:/etc/toydb.yaml
      - ./toydb5/data:/var/lib/toydb
    networks:
      toydb:
        ipv4_address: 172.20.0.105
    ports:
      - 9605:9605
